### ISSUE TITLE
Apparent VRP Paradox

### ISSUE THREAD

**Issue by juanluisrto** [VROOM-Project/pyvroom#81] opened 2023-07-04 19:30 UTC
I have run an experiment with pyvroom and have obtained some strange results. 
I'd like to share them here in case someone knows why this happens or in case it opens the door to identifying some bug. 

My experiment consists in solving a VRP in two different ways in order to compare their total cost / duration.
* I define a set of `jobs` at random locations with random weights and a set of `vehicles` also initialized at random (coordinates are sampled uniformly inside a circle)
* For the first way, I solve a regular VRP which we call `simple_vrp = VRP(jobs, vehicles)`
* For the second way:
     - I split my fleet of vehicles in two by half. So now I have `vehicles_first, vehicles_second`
     - I solve a VRP with all the jobs but only the first half  of vehicles `split_first_vrp = VRP(jobs, vehicles_first)`
     - I retrieve the unassigned jobs from that VRP `jobs_left = split_first_vrp.unassigned`
     - I solve a second VRP with the other half of the fleet but only for the remaining jobs: `split_second_vrp = VRP(jobs_left, vehicles_second)`
     
So I am comparing the total cost of the `simple_vrp` vs the sums of the costs of `split_first_vrp` and `split_second_vrp`.
The paradox is that sometimes `cost(simple_vrp) > cost(split_first_vrp) + cost(split_second_vrp)`
This is completely counterintuitive to me, since the solver should be able to optimize the fleet usage when knowing all the vehicles available, compared to solving with a subset of the vehicles and then completing the jobs left with the rest of vehicles.

To reproduce this behaviour, here is some code:

```python
import vroom
import numpy as np
import math
from scipy.spatial.distance import cdist


def generate_random_points( center : tuple, n: int, r: float, seed: int = 42):
    "Generates n uniformly distributed random points around a center point within a radius r"
    rng = np.random.default_rng(seed=seed)
    points = []
    cx, cy = center

    for _ in range(n):
        angle = rng.uniform(0, 2 * math.pi)
        distance = rng.uniform(0, r)
        dx = distance * math.cos(angle)
        dy = distance * math.sin(angle)
        new_point = (cx + dx, cy + dy)
        points.append(new_point)

    return points

N_JOBS = 400
N_VEHICLES = 8

SPLIT = int(N_VEHICLES/2) # index at which the fleet is split (half)

center = (0,0)

jobs_loc = generate_random_points(center, N_JOBS, r = 1)
vehicles_loc = generate_random_points(center, N_VEHICLES, r = 0.4)
points = jobs_loc + vehicles_loc

# Calculate the Euclidean distance matrix
fake_duration_matrix = cdist(points, points, metric='euclidean') * 100



def define_and_solve_vrp(jobs, vehicles):
    problem = vroom.Input()
    
    problem.set_durations_matrix(
        profile="car",
        matrix_input=fake_duration_matrix,
    )
    problem.add_job(jobs)
    problem.add_vehicle(vehicles)
    return problem.solve(exploration_level=5, nb_threads=4)
    

jobs = [vroom.Job(i, location = points.index(loc)) for i, loc in enumerate(jobs_loc)]
vehicles = [vroom.Vehicle(i,
                      start=points.index(loc),
                      end=points.index(loc)            
                     )
            for i, loc in enumerate(vehicles_loc)]
           
# We solve the VRP for all jobs and vehicles
simple_vrp_solution = define_and_solve_vrp(jobs, vehicles)

# We split the fleet
vehicles_first, vehicles_second = vehicles[:SPLIT], vehicles[SPLIT:]

# We solve the first part of the VRP with 
split_first_vrp_solution = define_and_solve_vrp(jobs, vehicles_first)

jobs_left = []

# We recreate the remaining jobs
for job in split_first_vrp_solution.unassigned:
    i = job.index()
    loc = jobs_loc[i]
    jobs_left.append(
        vroom.Job(i, location = points.index(loc))
    )

# We solve the second part of the VRP with the jobs left from the first part 
split_second_vrp_solution = define_and_solve_vrp(jobs_left, vehicles_second)


normal_vrp_cost = simple_vrp_solution.summary.cost 
split_vrp_cost = (split_first_vrp_solution.summary.cost + split_second_vrp_solution.summary.cost)

n_done_jobs_simple = N_JOBS - len(simple_vrp_solution.unassigned)
n_done_jobs_split  = N_JOBS - len(split_second_vrp_solution.unassigned)


print(f"normal_vrp_cost = {normal_vrp_cost} - Nº completed jobs = {n_done_jobs_simple}")
print(f" split_vrp_cost = {split_vrp_cost} - Nº completed jobs = {n_done_jobs_split}")
print(f"Paradox? = {normal_vrp_cost > split_vrp_cost}")


```
With this configuration the output of the program is:
```
>>>normal_vrp_cost = 2350 - Nº completed jobs = 400
>>> split_vrp_cost = 2340 - Nº completed jobs = 400
>>>Paradox? = True
```
There are many other configurations in which this happens (N_JOBS = 100, N_VEHICLES = 3), although it's not the usual case.
Do you know why this could be happening? Surely not related to pyvroom per se and its more on the vroom side

**Comment by jonathf** [comment] 2023-07-05 04:17
I am not sure if I agree. Vroom is designed to optimize on the problem here and now, not on some potential larger question it doesn't know about yet. I'm not surpriced at all that sometimes the cost is a little higher like that.

That said, you are right that this is a vroom issue. @jcoupey do you want to add your two cents?

**Comment by jcoupey** [comment] 2023-07-05 06:14
First, in principle there is no guarantee that you'll get `normal_vrp_cost <= split_vrp_cost`. This could indeed sound weird since the "normal" instance does have a more global view of the problem, but you'd only get this kind of assurance if we were to provide guaranteed optimal solutions.

That said, I suspect there is something else going on here related to the specific setup you're trying.

> I define a set of jobs at random locations with random weights 

Do you mean capacity restriction by "weights"? In your code there is no constraint whatsoever so basically there is nothing preventing any vehicle to handle **all** jobs in a very long route. Thus I'd be surprised if `jobs_left` is not empty for your second solving round.

> Surely not related to pyvroom per se and its more on the vroom side

Yes. Is there a convenient way to serialize the problem instances to the "usual" json format from `pyvroom`? That would make things easier to actually look at the instances and reproduce.

**Comment by jonathf** [comment] 2023-07-05 09:17
Pyvroom supports reading json format on input, and writing json for solutions. It does not support writing json for input. Is that supported in upstream vroom?

**Comment by juanluisrto** [comment] 2023-07-05 09:33
Thanks for the insights to both of you, I understand that there are no guarantees of getting more optimal solutions with more vehicles. It just seemed to me weird enough to flag it. 
Regarding the capacity restrictions, forget what I said. I removed those constraints and realized this behaviour still occurred (also removed `max_travel_time`), so now I'm just running unconstrained VRPs. 

@jcoupey Its true that jobs_left was many times empty, unless the jobs were sufficiently close to the initial location of another vehicle.

I have now simplified my experiment and run some tests.
The new setup is the following, given a set of `jobs`  and a set of `vehicles`: 
1. Generate all possible fleets from the set of vehicles (any subset of 1 or more vehicles)
2. For each fleet, solve the VRP for all jobs, record its cost
3. identify the minimum cost to solve the VRP for 1,2,3 ... vehicles

I run this experiment 5 times with different amounts of jobs (`N_JOBS =  [10, 50, 100, 150, 200]`) and fleets of up to 8 vehicles and here are the results. 

Highlighted in yellow is you can see the minimum cost needed to solve each VRP (columns). It's notable that for the VRP with 150 Jobs, the solution with 1 vehicle outperforms any other solution with up to 8 vehicles.

<img width="326" alt="image" src="https://github.com/VROOM-Project/pyvroom/assets/11667449/f177281e-8351-42d6-b79c-8d6f598422d5">

**Comment by jcoupey** [comment] 2023-07-05 16:20
> Its true that jobs_left was many times empty, unless the jobs were sufficiently close to the initial location of another vehicle

I don't get that: if you have no constraint, any number of vehicles should be able to handle **all** jobs. If you have no constraint and `jobs_left` is not **always** empty then there is something else screwed in your setup.

> It's notable that for the VRP with 150 Jobs, the solution with 1 vehicle outperforms any other solution with up to 8 vehicles.

Hard to draw any conclusion on optimization performance without knowing how your vehicles are defined:

- if all vehicles have the same start/end locations, then it's always cheaper to use a single vehicle if the constraints allows it;
- if vehicles are geographically distributed, then using more vehicles can lower the cost.

In the latter case, it's not a matter of having a "better" solution, it's simply about using vehicles that are closer to the jobs.

**Comment by jcoupey** [comment] 2023-07-05 16:24
@jonathf no we don't have an ability to serialize the problem to json upstream because usually it's already defined as json in input (that is except for the folks using the C++ libvroom API, kind of a similar situation as the one with pyvroom).

**Comment by jcoupey** [comment] 2023-07-13 22:57
@juanluisrto really appreciate the efforts to narrow this down to a minimal example! The one you have here looks like it you be pretty straightforward to translate to the upstream json format. Do you think you could post that in a dedicated upstream ticket? This would both ease looking the problem up (at least for me), and allow to close this ticket that is not related to pyvroom per say any more.

**Closed** 2023-07-14 17:14 UTC
